In [8]:
import numpy as np
from sklearn import metrics

In [6]:
# FAKE DATA
pred = [np.random.randint(0,2) for i in range(100)]
golden = [np.random.randint(0,2) for i in range(100)]

In [34]:
def get_metrics_yn(golden,pred):
    
    accuracy_score = metrics.accuracy_score(golden, pred)
    print(f'Accuracy: {100 * round(accuracy_score,7)}%')
    
    f1_yes = metrics.f1_score(golden, pred, average = 'binary', pos_label=1)
    print(f'F1_yes: {100 * round(f1_yes,7)}%')
    
    f1_no= metrics.f1_score(golden, pred, average = 'binary', pos_label=0)
    print(f'F1_no: {100 * round(f1_no,7)}%')
    
    macro_f1 = metrics.f1_score(golden, pred, average = 'macro')
    print(f'macroF1: {100 * round(macro_f1,7)}%')
    
    confusion_matrix = metrics.confusion_matrix(golden, pred)
    print(confusion_matrix)
    
    return accuracy_score, f1_yes, f1_no, macro_f1

In [31]:
import pandas as pd

In [52]:
all_metrics_df = pd.DataFrame({'batch': [],
                              'Acc': [],
                              'F1_yes': [],
                              'F1_no': [],
                              'Macro_F1': []})

In [53]:
for i in range(1,6):    
    test_df = pd.read_csv(f'../predict/predictions_yesno/8b_{i}_pred.csv')
    test_metrics = [i] + list(get_metrics_yn(test_df.gold, test_df.pred))
    all_metrics_df.loc[i] = test_metrics

Accuracy: 87.7551%
F1_yes: 92.96875%
F1_no: 52.63158%
macroF1: 72.80016%
[[ 10  12]
 [  6 119]]
Accuracy: 83.33333%
F1_yes: 90.44944000000001%
F1_no: 34.61538%
macroF1: 62.532410000000006%
[[ 18  38]
 [ 30 322]]
Accuracy: 83.68056%
F1_yes: 87.66404%
F1_no: 75.89744%
macroF1: 81.78074%
[[ 74  30]
 [ 17 167]]
Accuracy: 66.14583%
F1_yes: 76.01476000000001%
F1_no: 42.47788%
macroF1: 59.24632%
[[ 24  48]
 [ 17 103]]
Accuracy: 63.87665%
F1_yes: 65.83333%
F1_no: 61.68224%
macroF1: 63.75779%
[[66 63]
 [19 79]]


In [54]:
all_metrics_df

batch       Acc    F1_yes     F1_no  Macro_F1
1    1.0  0.877551  0.929688  0.526316  0.728002
2    2.0  0.833333  0.904494  0.346154  0.625324
3    3.0  0.836806  0.876640  0.758974  0.817807
4    4.0  0.661458  0.760148  0.424779  0.592463
5    5.0  0.638767  0.658333  0.616822  0.637578